#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -z $1 ] && [ $1 == "-h" ]; then
    echo "-h help"
    echo "-u username"
    echo "-p password"
    echo "-status show cluster status"
    echo "-pause cluster check pause"
    echo "-resume cluster check resume"
    echo "-watchMode [A|M] set watch strategy  A:availability, M:manual"
    echo "-switchOver 192.168.1.22:5432 switch to selected slave"
    echo "-reinit 192.168.1.22:5432 re-initialize selected slave with pg_rewind or pg_basebackup"
    echo "-encrypt clearString  encrpyt the clear string for use encrypted bfm password function"
    echo "-sync change replication type async to sync on selected slave (use slave application name instead of ip addr)"
    echo "-async change replication type sync to async on selected slave (use slave application name instead of ip addr)"
fi

if [ ! -z $1 ] && [ ! -z $2 ] && [ $1 == "-u" ]; then
    export clsUser=$2
fi

if [ ! -z $1 ] && [ ! -z $2 ] && [ $1 == "-p" ]; then
    export clsPwd=$2
fi

if [ ! -z $1 ] && [ $1 == "-status" ]; then
    export clsCommand="status"
fi

if [ ! -z $1 ] && [ $1 == "-pause" ]; then
    export clsCommand="pause"
fi

if [ ! -z $1 ] && [ $1 == "-resume" ]; then
    export clsCommand="resume"
fi

if [ ! -z $1 ] && [ $1 == "-mailPause" ]; then
    export clsCommand="mail-pause"
fi

if [ ! -z $1 ] && [ $1 == "-mailResume" ]; then
    export clsCommand="mail-resume"
fi

if [ ! -z $1 ]  && [ ! -z $2 ] && [ $1 == "-switchOver" ]; then
    export clsCommand="switchOver"
    export targetSlave=$2
fi

if [ ! -z $1 ]  && [ ! -z $2 ] && [ $1 == "-watchMode" ]; then
    export clsCommand="strategy"
    export clsStrategy=$2
fi

if [ ! -z $1 ]  && [ ! -z $2 ] && [ $1 == "-encrypt" ]; then
    export clsCommand="encrypt"
    export clearStr=$2
fi

if [ ! -z $1 ]  && [ ! -z $2 ] && [ $1 == "-sync" ]; then
    export clsCommand="sync"
    export targetSlave=$2
fi

if [ ! -z $1 ]  && [ ! -z $2 ] && [ $1 == "-async" ]; then
    export clsCommand="async"
    export targetSlave=$2
fi

if [ ! -z $2 ] && [ ! -z $3 ] && [ $2 == "-u" ]; then
    export clsUser=$3
fi

if [ ! -z $2 ] && [ ! -z $3 ] && [ $2 == "-p" ]; then
    export clsPwd=$3
fi

if [ ! -z $2 ] && [ $2 == "-status" ]; then
    export clsCommand="status"
fi

if [ ! -z $2 ] && [ $2 == "-pause" ]; then
    export clsCommand="pause"
fi

if [ ! -z $2 ] && [ $2 == "-resume" ]; then
    export clsCommand="resume"
fi

if [ ! -z $2 ] && [ $2 == "-mailPause" ]; then
    export clsCommand="mail-pause"
fi

if [ ! -z $2 ] && [ $2 == "-mailResume" ]; then
    export clsCommand="mail-resume"
fi

if [ ! -z $2 ]  && [ ! -z $3 ] && [ $2 == "-switchOver" ]; then
    export clsCommand="switchOver"
    export targetSlave=$3
fi

if [ ! -z $2 ]  && [ ! -z $3 ] && [ $2 == "-watchMode" ]; then
    export clsCommand="strategy"
    export clsStrategy=$3
fi

if [ ! -z $2 ]  && [ ! -z $3 ] && [ $2 == "-encrypt" ]; then
    export clsCommand="encrypt"
    export clearStr=$3
fi

if [ ! -z $2 ]  && [ ! -z $3 ] && [ $2 == "-sync" ]; then
    export clsCommand="sync"
    export targetSlave=$3
fi

if [ ! -z $2 ]  && [ ! -z $3 ] && [ $2 == "-async" ]; then
    export clsCommand="async"
    export targetSlave=$3
fi

if [ ! -z $3 ] && [ ! -z $4 ] &&[ $3 == "-u" ]; then
    export clsUser=$4
fi

if [ ! -z $3 ] && [ ! -z $4 ] && [ $3 == "-p" ]; then
    export clsPwd=$4
fi

if [ ! -z $3 ] && [ $3 == "-status" ]; then
    export clsCommand="status"
fi

if [ ! -z $3 ] && [ $3 == "-pause" ]; then
    export clsCommand="pause"
fi

if [ ! -z $3 ] && [ $3 == "-resume" ]; then
    export clsCommand="resume"
fi

if [ ! -z $3 ] && [ $3 == "-mailPause" ]; then
    export clsCommand="mail-pause"
fi

if [ ! -z $3 ] && [ $3 == "-mailResume" ]; then
    export clsCommand="mail-resume"
fi

if [ ! -z $3 ]  && [ ! -z $4 ] && [ $3 == "-switchOver" ]; then
    export clsCommand="switchOver"
    export targetSlave=$4
fi

if [ ! -z $3 ]  && [ ! -z $4 ] && [ $3 == "-reinit" ]; then
    export clsCommand="reinit"
    export targetSlave=$4
fi

if [ ! -z $3 ]  && [ ! -z $4 ] && [ $3 == "-watchMode" ]; then
    export clsCommand="strategy"
    export clsStrategy=$4
fi

if [ ! -z $3 ]  && [ ! -z $4 ] && [ $3 == "-encrypt" ]; then
    export clsCommand="encrypt"
    export clearStr=$4
fi

if [ ! -z $3 ]  && [ ! -z $4 ] && [ $3 == "-sync" ]; then
    export clsCommand="sync"
    export targetSlave=$4
fi

if [ ! -z $3 ]  && [ ! -z $4 ] && [ $3 == "-async" ]; then
    export clsCommand="async"
    export targetSlave=$4
fi

if [ ! -z $4 ] && [ $4 == "-status" ]; then
    export clsCommand="status"
fi

if [ ! -z $4 ] && [ $4 == "-pause" ]; then
    export clsCommand="pause"
fi

if [ ! -z $4 ] && [ $4 == "-resume" ]; then
    export clsCommand="resume"
fi

if [ ! -z $4 ] && [ $4 == "-mailPause" ]; then
    export clsCommand="mail-pause"
fi

if [ ! -z $4 ] && [ $4 == "-mailResume" ]; then
    export clsCommand="mail-resume"
fi

if [ ! -z $4 ]  && [ ! -z $5 ] && [ $4 == "-switchOver" ]; then
    export clsCommand="switchOver"
    export targetSlave=$5
fi

if [ ! -z $4 ]  && [ ! -z $5 ] && [ $4 == "-reinit" ]; then
    export clsCommand="reinit"
    export targetSlave=$5
fi

if [ ! -z $4 ]  && [ ! -z $5 ] && [ $4 == "-watchMode" ]; then
    export clsCommand="strategy"
    export clsStrategy=$5
fi

if [ ! -z $4 ]  && [ ! -z $5 ] && [ $4 == "-encrypt" ]; then
    export clsCommand="encrypt"
    export clearStr=$5
fi

if [ ! -z $4 ]  && [ ! -z $5 ] && [ $4 == "-sync" ]; then
    export clsCommand="sync"
    export targetSlave=$5
fi

if [ ! -z $4 ]  && [ ! -z $5 ] && [ $4 == "-async" ]; then
    export clsCommand="async"
    export targetSlave=$5
fi

if [ ! -z $5 ] && [ $5 == "-status" ]; then
    export clsCommand="status"
fi

if [ ! -z $5 ] && [ $5 == "-pause" ]; then
    export clsCommand="pause"
fi

if [ ! -z $5 ] && [ $5 == "-resume" ]; then
    export clsCommand="resume"
fi

if [ ! -z $5 ] && [ $5 == "-mailPause" ]; then
    export clsCommand="mail-pause"
fi

if [ ! -z $5 ] && [ $5 == "-mailResume" ]; then
    export clsCommand="mail-resume"
fi

if [ ! -z $5 ]  && [ ! -z $6 ] && [ $5 == "-switchOver" ]; then
    export clsCommand="switchOver"
    export targetSlave=$6
fi

if [ ! -z $5 ]  && [ ! -z $6 ] && [ $5 == "-reinit" ]; then
    export clsCommand="reinit"
    export targetSlave=$6
fi

if [ ! -z $5 ]  && [ ! -z $6 ] && [ $5 == "-watchMode" ]; then
    export clsCommand="strategy"
    export clsStrategy=$6
fi

if [ ! -z $5 ]  && [ ! -z $6 ] && [ $5 == "-encrypt" ]; then
    export clsCommand="encrypt"
    export clearStr=$6
fi

if [ ! -z $5 ]  && [ ! -z $6 ] && [ $5 == "-sync" ]; then
    export clsCommand="sync"
    export targetSlave=$6
fi

if [ ! -z $5 ]  && [ ! -z $6 ] && [ $5 == "-async" ]; then
    export clsCommand="async"
    export targetSlave=$6
fi

if [ -z $clsUser ] || [ -z $clsPwd ]; then
    echo "user or password NOT set. "
else
    if [ -f "$SCRIPT_DIR/application.properties" ]; then
        export bfmPair=$(cat "$SCRIPT_DIR/application.properties" |grep watcher.cluster-pair |cut -d "=" -f 2 |tr -d " ")
        export bfmSSL=$(cat "$SCRIPT_DIR/application.properties" |grep bfm.use-tls |cut -d "=" -f 2 |tr -d " ")
        export bfmPort=$(cat "$SCRIPT_DIR/application.properties" |grep watcher.cluster-port |cut -d "=" -f 2 |tr -d " ")
    elif [ -f ./application.properties ]; then
        export bfmPair=$(cat ./application.properties |grep watcher.cluster-pair |cut -d "=" -f 2 |tr -d " ")
        export bfmSSL=$(cat ./application.properties |grep bfm.use-tls |cut -d "=" -f 2 |tr -d " ")
        export bfmPort=$(cat ./application.properties |grep watcher.cluster-port |cut -d "=" -f 2 |tr -d " ")
    else
        export bfmPair='127.0.0.1:9994'
        export bfmSSL='false'
        export bfmPort='9994'
    fi

    if [ ! -z $bfmSSL ] && [ $bfmSSL == "true" ]; then
        export bfmProtocol='https'
    else
        export bfmProtocol='http'
    fi

    export pair_active=$(curl -k -s $bfmProtocol://$bfmPair/bfm/get-active-bfm -u $clsUser:$clsPwd)
    #echo $pair_active

    if [ ! -z $pair_active ] && [ $pair_active == "T" ]; then
        export active_bfm=$bfmPair
    else
        export active_bfm="127.0.0.1:"$bfmPort
    fi

    echo -e "\nActive BFM :"$active_bfm
    if [ ! -z $clsCommand ] && [ $clsCommand == "status" ]; then
        curl -k -X GET $bfmProtocol://$active_bfm/bfm/cluster-status -u $clsUser:$clsPwd        
    elif [ ! -z $clsCommand ] && [ $clsCommand == "pause" ]; then
        curl -k -X GET $bfmProtocol://$active_bfm/bfm/check-pause -u $clsUser:$clsPwd
    elif [ ! -z $clsCommand ] && [ $clsCommand == "resume" ]; then
        curl -k -X GET $bfmProtocol://$active_bfm/bfm/check-resume -u $clsUser:$clsPwd
    elif [ ! -z $clsCommand ] && [ $clsCommand == "mail-pause" ]; then
        curl -k -X GET $bfmProtocol://$active_bfm/bfm/mail-pause -u $clsUser:$clsPwd
    elif [ ! -z $clsCommand ] && [ $clsCommand == "mail-resume" ]; then
        curl -k -X GET $bfmProtocol://$active_bfm/bfm/mail-resume -u $clsUser:$clsPwd        
    elif [ ! -z $clsCommand ] && [ $clsCommand == "strategy" ]; then
        curl -k -X POST  $bfmProtocol://$active_bfm/bfm/watch-strategy/$clsStrategy -u $clsUser:$clsPwd
    elif [ ! -z $clsCommand ] && [ $clsCommand == "switchOver" ]; then
        curl -k -X POST  $bfmProtocol://$active_bfm/bfm/switchover/$targetSlave -u $clsUser:$clsPwd
    elif [ ! -z $clsCommand ] && [ $clsCommand == "reinit" ]; then
        curl -k -X POST  $bfmProtocol://$active_bfm/bfm/reinit/$targetSlave -u $clsUser:$clsPwd     
    elif [ ! -z $clsCommand ] && [ $clsCommand == "encrypt" ]; then
        curl -k -X POST  $bfmProtocol://$active_bfm/bfm/encrypt/$clearStr -u $clsUser:$clsPwd
    elif [ ! -z $clsCommand ] && [ $clsCommand == "sync" ]; then
        curl -k -X POST  $bfmProtocol://$active_bfm/bfm/setsync/$targetSlave -u $clsUser:$clsPwd
    elif [ ! -z $clsCommand ] && [ $clsCommand == "async" ]; then
        curl -k -X POST  $bfmProtocol://$active_bfm/bfm/setasync/$targetSlave -u $clsUser:$clsPwd        
    else
        echo "command not found..."$clsCommand
    fi
fi
