services:
  minipg-node1:
    build:
      context: ../minipg
      dockerfile: Dockerfile
    container_name: minipg-node1
    ports:
      - "5432:5432"
      - "7779:7779"
    environment:
      PGPASSFILE: /config/.pgpass
      PGPASSWORD: postgres  
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/pgsql/16/data
      MINIPG_USE_TLS: "false"
      MINIPG_TLS_KEY_STORE: ""
      MINIPG_REPLICATION_NODES: ""  # birinci düğüm (master)
      PGAPPNAME=minipg-node1: 
    volumes:
      - minipg1_data:/var/lib/pgsql/16/data
      - ../minipg:/config:ro
    networks:
      bfm-net:
        aliases:
          - minipg-node1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  minipg-node2:
    build:
      context: ../minipg
      dockerfile: Dockerfile
    container_name: minipg-node2
    ports:
      - "5433:5432"
      - "7780:7779"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/pgsql/16/data
      PGPASSWORD: postgres
      PGPASSFILE: /config/.pgpass
      PGAPPNAME: minipg-node2
      MINIPG_USE_TLS: "false"
      MINIPG_TLS_KEY_STORE: ""
      MINIPG_REPLICATION_NODES: "minipg-node1:5432"
      MINIPG_REPLICATION_USER: "postgres"
      MINIPG_REPLICATION_PASSWORD: "postgres"
    volumes:
      - minipg2_data:/var/lib/pgsql/16/data
      - ../minipg:/config:ro
    networks:
      bfm-net:
        aliases:
          - minipg-node2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
  bfm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bfm
    depends_on:
      minipg-node1:
        condition: service_healthy
      minipg-node2:
        condition: service_healthy
    ports:
      - "9994:9994"
    environment:
      WATCHER_CLUSTER_PORT: "9994"
      MINIPG_PORT: "7779"
    volumes:
      - ./application.properties:/app/application.properties:ro
    networks:
      - bfm-net
    restart: unless-stopped

volumes:
  minipg1_data:
  minipg2_data:

networks:
  bfm-net:
    driver: bridge

