version: '3.8'

services:
  bfm-app:
    image: bfm-app:latest
    container_name: bfm-app
    build:
      context: /home/ekonak/bfm
      dockerfile: Dockerfile.pg16
    ports:
      - "9995:9995"  
  
    environment:
      
      - BFM_SERVER_HOST=minipg-node
      - BFM_SERVER_PORT=5432
      - BFM_SERVER_USERNAME=postgres
      - BFM_SERVER_PASSWORD=postgres
      - MINIPG_SECONDARY_HOST=minipg-node-slave
      - MINIPG_SECONDARY_PORT=5432  
      - MINIPG_SECONDARY_USERNAME=postgres
      - MINIPG_SECONDARY_PASSWORD=postgres
      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=false
     
      - POSTGRES_INITDB_ARGS="--data-checksums"
    networks:
      - bfm-net
    depends_on:
      - minipg-node
      - minipg-node-slave

  minipg-node:
    image: minipg-pg16:latest
    container_name: minipg-node
    build:
      context: /home/ekonak/mini-pg/app
      dockerfile: Dockerfile.pg16
    ports:
      - "5433:5432"   
      - "9998:9998"   
    environment:
      - ROLE=primary
      
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_CONFIGS=wal_level=replica,max_wal_senders=10,wal_keep_size=1GB,archive_mode=on,archive_command='test ! -f /archive/%f && cp %p /archive/%f',wal_log_hints=on,max_wal_size=2GB,min_wal_size=1GB
    volumes:
      - pg_primary_data:/var/lib/pgsql/data
      - pg_archive:/archive
    networks:
      - bfm-net

  minipg-node-slave:
    image: minipg-pg16:latest
    container_name: minipg-node-slave
    build:
      context: /home/ekonak/mini-pg/app
      dockerfile: Dockerfile.pg16
    ports:
      - "5434:5432"   
      - "9997:9997"   
    environment:
      - ROLE=slave

      - POSTGRES_INITDB_ARGS="--data-checksums"
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_CONFIGS=wal_level=replica,max_wal_senders=10,wal_keep_size=1GB,hot_standby=on,wal_log_hints=on,max_wal_size=2GB,min_wal_size=1GB
      - PRIMARY_HOST=minipg-node
      - PRIMARY_PORT=5432
      - RESTORE_COMMAND='cp /archive/%f %p'
    volumes:
      - pg_secondary_data:/var/lib/pgsql/data
      - pg_archive:/archive:ro
    networks:
      - bfm-net
    depends_on:
      - minipg-node

networks:
  bfm-net:
    driver: bridge

volumes:
  pg_primary_data:
  pg_secondary_data:
  pg_archive: